CREATE TABLE DEPARTMENT(
	DEPT_ID INT IDENTITY(1,1) PRIMARY KEY,
	DEPT_NAME VARCHAR(200) NOT NULL,
	HOD VARCHAR(200) NOT NULL,
	DEPT_EMAIL VARCHAR(200) NOT NULL,
	DEPT_CONTACTNUMBER VARCHAR(200) NOT NULL,
	CREATED_DATE_TIME DATETIME,
	UPDATED_DATE_TIME DATETIME
);
