CREATE TABLE ROLES(
	ROLE_ID INT IDENTITY(1,1) PRIMARY KEY,
	ROLE_NAME VARCHAR(200) NOT NULL,
	DEPARTMENT_NAME VARCHAR(200) NOT NULL,
	ROLE_DESCRIPTION VARCHAR(200) NOT NULL,
	CREATED_DATE_TIME DATETIME,
	UPDATED_DATE_TIME DATETIME 
);