CREATE TABLE TIMESHEET(
	TIMESHEET_ID INT IDENTITY(1,1) PRIMARY KEY,
	EMPLOYEE_ID INT,
	EMPLOYEE_NAME VARCHAR(200) NOT NULL,
	APPROVER_EMPLOYEE_NAME VARCHAR(200) NOT NULL,
	PROJECT_NAME VARCHAR(200) NOT NULL,
	TASK_DETAILS VARCHAR(200) NOT NULL,
	START_DATE DATE,
	END_DATE DATE,
    FOREIGN KEY(EMPLOYEE_ID) REFERENCES EMPLOYEE_DETAILS(EMPLOYEE_ID)

);