CREATE TABLE EMPLOYEE_WORK_EXPERIENCE(
  EMPLOYEE_WORK_EXP_ID INT IDENTITY(1,1) PRIMARY KEY,
  EMPLOYEE_ID INT,
  COMPANY_NAME VARCHAR(200) NOT NULL,
  DESIGNATION VARCHAR(200) NOT NULL,
  FROM_DATE DATE,
  TO_DATE DATE,
  FOREIGN KEY(EMPLOYEE_ID) REFERENCES EMPLOYEE_DETAILS(EMPLOYEE_ID)

);