CREATE procedure SP_add_TimeSheet(
    @EMPLOYEE_NAME VARCHAR(200),
	@APPROVER_EMPLOYEE_NAME VARCHAR(200),
	@PROJECT_NAME VARCHAR(200),
	@TASK_DETAILS VARCHAR(200),
	@START_DATE DATE,
	@END_DATE DATE,
	@APPROVER_STATUS VARCHAR(200)
)
AS
BEGIN
    INSERT INTO TIMESHEET(EMPLOYEE_NAME,APPROVER_EMPLOYEE_NAME,PROJECT_NAME,TASK_DETAILS,START_DATE,END_DATE,APPROVER_STATUS,CREATED_DATE_TIME) VALUES(@EMPLOYEE_NAME,@APPROVER_EMPLOYEE_NAME,@PROJECT_NAME,@TASK_DETAILS,@START_DATE,@END_DATE,@APPROVER_STATUS,GETDATE())

END