ALTER PROCEDURE SP_check_allEmployeeDetails(
	@EMAIL_ID VARCHAR(200),
	@CONTACT_NUMBER VARCHAR(200),
	@PANCARD_NUMBER VARCHAR(200),
	@AADHAR_NUMBER VARCHAR(200)
)
AS
BEGIN
   SELECT * FROM EMPLOYEE_DETAILS WHERE EMAIL_ID = @EMAIL_ID OR CONTACT_NUMBER = @CONTACT_NUMBER OR PANCARD_NUMBER = @PANCARD_NUMBER OR AADHAR_NUMBER  = @AADHAR_NUMBER 
END
