ALTER PROCEDURE SP_delete_allEmployeesDetails(
     @id INT
    )
AS
BEGIN
	IF EXISTS (SELECT * FROM EMPLOYEE_WORK_EXPERIENCE WHERE EMPLOYEE_ID = @id) 
	BEGIN
		DELETE FROM EMPLOYEE_WORK_EXPERIENCE 
		WHERE EMPLOYEE_ID  = @id
    END
    IF EXISTS (SELECT * FROM EMPLOYEE_EDUCATION WHERE EMPLOYEE_ID = @id)
	BEGIN    
		DELETE FROM EMPLOYEE_EDUCATION 
	    WHERE EMPLOYEE_ID =@id
	END
    
    IF EXISTS (SELECT * FROM EMPLOYEE_ADDRESS WHERE EMPLOYEE_ID =@id)
	BEGIN  
        DELETE FROM EMPLOYEE_ADDRESS 
        WHERE EMPLOYEE_ID =@id     
    END
    
    IF EXISTS (SELECT * FROM LEAVES WHERE EMPLOYEE_ID = @id)
	BEGIN  
        DELETE FROM LEAVES 
        WHERE EMPLOYEE_ID = @id
    END
   
    IF EXISTS (SELECT * FROM TIMESHEET WHERE EMPLOYEE_ID  = @id)
	BEGIN  
        DELETE FROM TIMESHEET 
        WHERE EMPLOYEE_ID  = @id
    END

    IF EXISTS (SELECT * FROM EMPLOYEE_DETAILS WHERE EMPLOYEE_ID =@id)
	BEGIN  
        DELETE FROM EMPLOYEE_DETAILS 
        WHERE EMPLOYEE_ID =@id
    END

END