CREATE PROCEDURE SP_edit_projects(
	@PROJECT_ID INT,
	@PROJECT_NAME VARCHAR(200),
	@START_DATE DATE,
	@END_DATE DATE,
	@PROJECT_MANAGER VARCHAR(200)
)
AS
BEGIN
	UPDATE PROJECTS 
	SET 
		PROJECT_NAME = @PROJECT_NAME,
		START_DATE = @START_DATE,
		END_DATE = @END_DATE,
		PROJECT_MANAGER = @PROJECT_MANAGER,
		UPDATED_DATE_TIME =GETDATE()
	WHERE PROJECT_ID =@PROJECT_ID
END