
CREATE PROCEDURE SP_edit_roles (
    @ROLE_ID INT,
	@ROLE_NAME  varchar(200),
    @DEPARTMENT_NAME varchar(200),
    @ROLE_DESCRIPTION varchar(200)

)

AS
BEGIN
	UPDATE ROLES 
	SET 
	ROLE_NAME = @ROLE_NAME , 
    DEPARTMENT_NAME = @DEPARTMENT_NAME ,
    ROLE_DESCRIPTION = @ROLE_DESCRIPTION,
	UPDATED_DATE_TIME =GETDATE()
	WHERE ROLE_ID =@ROLE_ID
END

