
CREATE PROCEDURE SP_edit_department(
	@DEPT_ID INT,
	@DEPT_NAME VARCHAR(200),
	@HOD VARCHAR(200),
	@DEPT_EMAIL VARCHAR(200),
	@DEPT_CONTACTNUMBER VARCHAR(200)
)
AS
BEGIN
	UPDATE DEPARTMENT  
	SET 
		DEPT_NAME = @DEPT_NAME,
		HOD = @HOD,
		DEPT_EMAIL = @DEPT_EMAIL,
		DEPT_CONTACTNUMBER = @DEPT_CONTACTNUMBER,
		UPDATED_DATE_TIME =GETDATE()
	WHERE DEPT_ID =@DEPT_ID
END