ALTER PROCEDURE SP_edit_leaves(
	@LEAVE_REQUEST_ID INT,
	@EMPLOYEE_NAME VARCHAR(200),
	@APPROVER_NAME VARCHAR(200),
	@REASON_FOR_LEAVE VARCHAR(200),
	@START_DATE DATE,
	@END_DATE DATE,
	@LEAVES_STATUS VARCHAR(200)
)

AS
BEGIN
	 UPDATE LEAVES 
        SET
        EMPLOYEE_NAME=@EMPLOYEE_NAME,
		APPROVER_NAME=@APPROVER_NAME,
		REASON_FOR_LEAVE =@REASON_FOR_LEAVE,
        START_DATE = @START_DATE,
        END_DATE = @END_DATE,
		LEAVES_STATUS=@LEAVES_STATUS,
        UPDATED_DATE_TIME = GETDATE()
    WHERE LEAVE_REQUEST_ID = @LEAVE_REQUEST_ID
END
