ALTER PROCEDURE SP_edit_leaves(
	@EMPLOYEE_ID INT,
	@APPROVER_NAME VARCHAR(200),
	@REASON_FOR_LEAVE VARCHAR(200),
	@START_DATE DATE,
	@END_DATE DATE,
	@LEAVES_STATUS VARCHAR(200)
)

AS
BEGIN
	 UPDATE LEAVES 
        SET 
		APPROVER_NAME=@APPROVER_NAME,
		REASON_FOR_LEAVE =@REASON_FOR_LEAVE,
        START_DATE = @START_DATE,
        END_DATE = @END_DATE,
		LEAVES_STATUS=@LEAVES_STATUS,
        UPDATED_DATE_TIME = GETDATE()
    WHERE EMPLOYEE_ID = @EMPLOYEE_ID
END