ALTER procedure SP_edit_TimeSheet(
     @TIMESHEET_ID INT,
    @EMPLOYEE_NAME VARCHAR(200),
	@APPROVER_EMPLOYEE_NAME VARCHAR(200),
	@PROJECT_NAME VARCHAR(200),
	@TASK_DETAILS VARCHAR(200),
	@START_DATE DATE,
	@END_DATE DATE,
	@APPROVER_STATUS VARCHAR(200)
)
AS
BEGIN
     UPDATE TIMESHEET 
    SET 
        EMPLOYEE_NAME = @EMPLOYEE_NAME,
	    APPROVER_EMPLOYEE_NAME =@APPROVER_EMPLOYEE_NAME,
        PROJECT_NAME =@PROJECT_NAME,
        TASK_DETAILS=@TASK_DETAILS,
        START_DATE=@START_DATE,
        END_DATE=@END_DATE,
        APPROVER_STATUS=@APPROVER_STATUS,
        UPDATED_DATE_TIME = GETDATE()
    WHERE  TIMESHEET_ID = @TIMESHEET_ID

END