ALTER PROCEDURE SP_get_allEmployeeDetails
AS
BEGIN
SELECT ed.EMPLOYEE_ID ,ed.FIRST_NAME,ed.MIDDLE_NAME ,ed.LAST_NAME ,ed.GENDER ,ed.CONTACT_NUMBER ,ed.EMAIL_ID ,ed.PANCARD_NUMBER ,ed.DOB ,ed.AADHAR_NUMBER,ed.EMPLOYEE_NUMBER,ed.DATE_OF_JOINING ,ed.LAST_WORKING_DAY ,ed.BLOOD_GROUP ,ed.ACTIVATION_STATUS ,ed.DEPT_ID,ed.PROJECT_ID,ed.ROLE_ID,ea.PERMANENT_ADDRESS,ea.HOUSE_NO,ea.STREET_NAME,ea.CITY,ea.DISTRICT,ea.STATE,ea.PINCODE,ea.COUNTRY,ea.TEMPORARY_ADDRESS,ea.T_HOUSE_NO,ea.T_STREET_NAME,ea.T_CITY,ea.T_DISTRICT,ea.T_STATE,ea.T_PINCODE,ea.T_COUNTRY, ewe.COMPANY_NAME,ewe.DESIGNATION,ewe.FROM_DATE,ewe.TO_DATE, ee.TENTH,ee.BOARD_NAME,ee.PASSEDOUT_YEAR,ee.PERCENTAGE,ee.INTERMEDIATE,ee.INTER_BOARD_NAME,ee.INTER_PASSEDOUT_YEAR,ee.INTER_PERCENTAGE,ee.GRADUATION,ee.UG_UNIVERSITY,ee.UG_PASSEDOUT_YEAR,ee.UG_PERCENTAGE,ee.POST_GRADUTATION ,ee.PG_UNIVERSITY,ee.PG_PASSEDOUT_YEAR,ee.PG_PERCENTAGE
	FROM EMPLOYEE_DETAILS ed
	INNER JOIN EMPLOYEE_ADDRESS ea ON ed.EMPLOYEE_ID=ea.EMPLOYEE_ID
	INNER JOIN EMPLOYEE_WORK_EXPERIENCE ewe ON ed.EMPLOYEE_ID=ewe.EMPLOYEE_ID
	INNER JOIN EMPLOYEE_EDUCATION ee ON ed.EMPLOYEE_ID=ee.EMPLOYEE_ID;

END;