CREATE PROCEDURE SP_get_leavesApproveStatus
@EMPLOYEE_ID int ,
@LEAVES_STATUS varchar(200)

AS
BEGIN
SELECT LEAVES_STATUS 
FROM LEAVES WHERE EMPLOYEE_ID=@EMPLOYEE_ID AND LEAVES_STATUS=@LEAVES_STATUS 
END