CREATE  PROCEDURE SP_get_idBased_timesheet(
@EMPLOYEE_ID INT,
@START_DATE date,
@END_DATE date
)
AS
BEGIN
	DECLARE @APPROVE_TIMESHEET varchar(200)
    set @APPROVE_TIMESHEET = (SELECT pm.APPROVE_TIMESHEET 
    FROM EMPLOYEE_DETAILS ed 
    INNER JOIN PERMISSION_MANAGMENT pm ON ed.ROLE_ID = pm.ROLE_ID
    WHERE EMPLOYEE_ID = @EMPLOYEE_ID)
    IF @APPROVE_TIMESHEET='true'
    BEGIN
        SELECT *
        FROM TIMESHEET
		WHERE EMPLOYEE_ID = @EMPLOYEE_ID AND START_DATE BETWEEN @START_DATE AND @END_DATE
       ORDER BY TIMESHEET_ID DESC ;            
       END
     ELSE
     BEGIN
        SELECT *
        FROM TIMESHEET
		WHERE EMPLOYEE_ID = @EMPLOYEE_ID AND START_DATE BETWEEN @START_DATE AND @END_DATE
       ORDER BY TIMESHEET_ID DESC ;       
       END
END;
