ALTER  PROCEDURE SP_get_timesheetStatus
(	@TIMESHEET_ID INT,
	@EMPLOYEE_ID INT,
	
	@APPROVER_STATUS varchar(200)
)
AS
BEGIN
	UPDATE TIMESHEET 
	SET 
		APPROVER_STATUS=@APPROVER_STATUS
	WHERE  TIMESHEET_ID=@TIMESHEET_ID and EMPLOYEE_ID =@EMPLOYEE_ID 
END