CREATE PROCEDURE SP_post_leaves(
	@EMPLOYEE_NAME VARCHAR(200),
	@APPROVER_NAME VARCHAR(200),
	@REASON_FOR_LEAVE VARCHAR(200),
	@START_DATE DATE,
	@END_DATE DATE,
	@LEAVES_STATUS VARCHAR(200)
)
AS
BEGIN
	INSERT INTO LEAVES  (EMPLOYEE_NAME,APPROVER_NAME,REASON_FOR_LEAVE,START_DATE,END_DATE,LEAVES_STATUS,CREATED_DATE_TIME) VALUES(@EMPLOYEE_NAME,@APPROVER_NAME,@REASON_FOR_LEAVE,@START_DATE,@END_DATE,@LEAVES_STATUS,GETDATE())
END