CREATE PROCEDURE SP_post_projects(
	@PROJECT_NAME VARCHAR(200),
	@START_DATE DATE,
	@END_DATE DATE,
	@PROJECT_MANAGER VARCHAR(200)
	
)
AS
BEGIN
	INSERT INTO PROJECTS (PROJECT_NAME,START_DATE,END_DATE,PROJECT_MANAGER,CREATED_DATE_TIME) VALUES(@PROJECT_NAME,@START_DATE,@END_DATE,@PROJECT_MANAGER,@CREATED_DATE_TIME,GETDATE())
END